"""Membuat tabel Notifikasi

Revision ID: 7b4e7f359615
Revises: e997fd9d440e
Create Date: 2025-01-07 03:12:50.240974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4e7f359615'
down_revision = 'e997fd9d440e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifikasi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_transaksi', sa.Integer(), nullable=True),
    sa.Column('pesan', sa.Text(), nullable=False),
    sa.Column('tanggal_kirim', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_transaksi'], ['transaksi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifikasi')
    # ### end Alembic commands ###
