"""empty message

Revision ID: bf24f7f9a85e
Revises: 7b4e7f359615
Create Date: 2025-01-09 13:15:29.738825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf24f7f9a85e'
down_revision = '7b4e7f359615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layanan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_layanan', sa.String(length=100), nullable=False),
    sa.Column('harga_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pelanggan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('nomor_telepon', sa.String(length=15), nullable=False),
    sa.Column('alamat', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('nomor_telepon', sa.String(length=15), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('transaksi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pelanggan', sa.Integer(), nullable=False),
    sa.Column('id_layanan', sa.Integer(), nullable=False),
    sa.Column('berat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_harga', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Selesai'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_layanan'], ['layanan.id'], ),
    sa.ForeignKeyConstraint(['id_pelanggan'], ['pelanggan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifikasi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_transaksi', sa.Integer(), nullable=False),
    sa.Column('pesan', sa.Text(), nullable=False),
    sa.Column('tanggal_kirim', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_transaksi'], ['transaksi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifikasi')
    op.drop_table('transaksi')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('pelanggan')
    op.drop_table('layanan')
    # ### end Alembic commands ###
