"""Membuat tabel transaksi

Revision ID: e997fd9d440e
Revises: f3c2387e09b1
Create Date: 2025-01-07 03:06:31.134344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e997fd9d440e'
down_revision = 'f3c2387e09b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaksi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pelanggan', sa.Integer(), nullable=True),
    sa.Column('id_layanan', sa.Integer(), nullable=True),
    sa.Column('berat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_harga', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Selesai'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_layanan'], ['layanan.id'], ),
    sa.ForeignKeyConstraint(['id_pelanggan'], ['pelanggan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaksi')
    # ### end Alembic commands ###
