"""Membuat tabel Layanan

Revision ID: f3c2387e09b1
Revises: e155add9f1ea
Create Date: 2025-01-07 02:55:15.196063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c2387e09b1'
down_revision = 'e155add9f1ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layanan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_layanan', sa.String(length=100), nullable=False),
    sa.Column('harga_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('layanan')
    # ### end Alembic commands ###
